{
 "title": "Metrics2",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Chromatic Dispersion",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/chromatic-dispersion/avg"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/osnr/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Module Temp",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "select": [
      [
       {
        "params": [
         "/components/component/state/temperature/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "eSNR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/esnr/avg"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Carrier Offset Freq",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/carrier-frequency-offset/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/interfaces/interface/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/interfaces/interface/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface/state/high-speed"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wavelength DoM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "locale", "label": "Millions of Hz" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/transceiver/physical-channels/channel/state/output-frequency"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Instant Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/transceiver/physical-channels/channel/state/output-power/instant"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "/components/component/@name", "operator": "=", "value": "FPC0:PIC2:PORT10:Xcvr0" }
     ]
    }
   ]
  },
  {
   "title": "Wavelength OpenZR Specific",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "locale", "label": "Millions of Hz" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/frequency"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Instant Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/transceiver/physical-channels/channel/state/input-power/instant"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "/components/component/@name", "operator": "=", "value": "FPC0:PIC2:PORT10:Xcvr0" }
     ]
    }
   ]
  },
  {
   "title": "Pre-FEC bit error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/pre-fec-ber/avg"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PDL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/polarization-dependent-loss/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOPMD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/second-order-polarization-mode-dispersion/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FEC Uncorrected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/transceiver/state/fec-uncorrectable-blocks"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SOP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/sop-roc/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Laser Frequency Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/interfaces/interface/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/interfaces/interface/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/interfaces/interface/optics/frequency_error"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/chromatic-dispersion/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Laser bias current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/optical-channel/state/laser-bias-current/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/components/component/@name]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "/components/component/@name" ], "type": "tag" }
     ],
     "measurement": "optical",
     "query": "SELECT \"/components/component/optical-channel/state/output-power/instant\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/components/component/@name\"",
     "select": [
      [
       {
        "params": [
         "/components/component/state/temperature/instant"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DGD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/junos/interface-information/physical-interface/@name]] Lane [[tag_/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      {
       "params": [
        "/junos/interface-information/physical-interface/@name"
       ],
       "type": "tag"
      },
      {
       "params": [
        "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index"
       ],
       "type": "tag"
      }
     ],
     "measurement": "optical",
     "query": "SELECT \"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/lane-dgd\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/junos/interface-information/physical-interface/@name\", \"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index\"",
     "select": [
      [
       {
        "params": [
         "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/lane-dgd"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Laser Rx Optical Power mW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/junos/interface-information/physical-interface/@name]] Lane [[tag_/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      {
       "params": [
        "/junos/interface-information/physical-interface/@name"
       ],
       "type": "tag"
      },
      {
       "params": [
        "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index"
       ],
       "type": "tag"
      }
     ],
     "measurement": "optical",
     "query": "SELECT \"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/laser-rx-optical-power\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/junos/interface-information/physical-interface/@name\", \"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index\"",
     "select": [
      [
       {
        "params": [
         "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/laser-rx-optical-power"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_device]] [[tag_/junos/interface-information/physical-interface/@name]] Lane [[tag_/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      {
       "params": [
        "/junos/interface-information/physical-interface/@name"
       ],
       "type": "tag"
      },
      {
       "params": [
        "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index"
       ],
       "type": "tag"
      }
     ],
     "measurement": "optical",
     "query": "SELECT last(\"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/laser-rx-optical-power\") FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/junos/interface-information/physical-interface/@name\", \"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index\"",
     "select": [
      [
       {
        "params": [
         "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/laser-rx-optical-power"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Laser Tx Optical Power mW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "alias": "[[tag_device]] [[tag_/junos/interface-information/physical-interface/@name]] Lane [[tag_/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index]]",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      {
       "params": [
        "/junos/interface-information/physical-interface/@name"
       ],
       "type": "tag"
      },
      {
       "params": [
        "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index"
       ],
       "type": "tag"
      }
     ],
     "measurement": "optical",
     "query": "SELECT \"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/laser-rx-optical-power\" FROM \"optical\" WHERE $timeFilter GROUP BY \"device\", \"/junos/interface-information/physical-interface/@name\", \"/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/@lane-index\"",
     "select": [
      [
       {
        "params": [
         "/junos/interface-information/physical-interface/optics-diagnostics/optics-diagnostics-lane-values/laser-output-power"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  }
 ]
}